### ISSUE TITLE
"reflect: call of reflect.Value.IsNil on struct Value" for struct error type

### ISSUE THREAD

**Issue by zikaeroh** [gotestyourself/gotest.tools#186]
The following code panics, as `NilError` is attempting to check `IsNil` on a non-pointer struct:

```
type structError struct{}

func (structError) Error() string {
	return "this is structError"
}

func TestStructError(t *testing.T) {
	var err error = structError{}
	assert.NilError(t, err)
}
```

```
--- FAIL: TestStructError (0.00s)
panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value

goroutine 21 [running]:
testing.tRunner.func1(0xc000110300)
	/usr/lib/go/src/testing/testing.go:874 +0x3a3
panic(0x59a640, 0xc000096120)
	/usr/lib/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.IsNil(...)
	/usr/lib/go/src/reflect/value.go:1073
gotest.tools/v3/assert.assert(0x60d4c0, 0xc000110300, 0xc00007ef00, 0x5dec38, 0x5a0360, 0x748a08, 0x0, 0x0, 0x0, 0x0)
	/home/jake/go/pkg/mod/gotest.tools/v3@v3.0.1/assert/assert.go:123 +0x773
gotest.tools/v3/assert.NilError(0x60d4c0, 0xc000110300, 0x609d80, 0x748a08, 0x0, 0x0, 0x0)
	/home/jake/go/pkg/mod/gotest.tools/v3@v3.0.1/assert/assert.go:249 +0x101
some.tld/baderr.TestStructError(0xc000110300)
	/home/jake/testproj/baderr/err_test.go:36 +0x60
testing.tRunner(0xc000110300, 0x5df150)
	/usr/lib/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:960 +0x350
FAIL	some.tld/baderr	0.009s
FAIL
```

The struct doesn't need to be empty; it can have values. Related to #167/#171.

However, I think #171 needs to be reverted anyway (#185), because a typed nil error is not "nil".

**Comment by zikaeroh** [comment]
Happy to just close this as noise if #185 is enough and the revert would happen anyway. Don't want to cause too much of a burden with double the issues...
